---
title: "Influence of the initialization"
author: Morgane Pierre-Jean
output: github_document
vignette: >
%\VignetteIndexEntry{Influence of the initialization}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[UTF-8]{inputenc}
  ---
  
  ```{r setup, include=FALSE}
  knitr::opts_chunk$set(echo = TRUE)
  ```
  
  ## Useful packages
  
  ```{r, library}
  library(Matrix)
library(tidyverse)
library(PintMF)
library(CrIMMix)
library(future)
library(mclust)
```

## Simulate data with CrIMMix package

```{r, simulations}
nclust <- 4
nByclust= c(5, 10, 25, 10)
```

```{r message=FALSE}
clust_function <- function(R){
  clust <- R$W %>% dist %>% hclust(method="ward.D2") %>% cutree(4)
}


perf <- do.call(rbind, lapply(1:20, function (ii){
  c_1 <- simulateY(nclust = nclust,  n_byClust = nByclust, J=100, prop=0.05, noise=0.2)
  c_2 <- simulateY(nclust = nclust,  n_byClust = nByclust, J=50, flavor="binary", params=list(c(p=0.6)), prop=0.1, noise=0.3)
  params_beta <- list(c(mean1=-1, mean2=1, sd1=0.5, sd2=0.5))
  c_3 <- simulateY(nclust = nclust,  n_byClust = nByclust, J=500,flavor="beta", params=params_beta, prop=0.2, noise=0.2)
  data <- list(c_1$data, c_2$data, c_3$data)
  data <- lapply(data, function (dd){
    colnames(dd) <- sprintf("gene%s",1:ncol(dd)) 
    dd
  })
  true.clust <- c_1$true.clusters
  print(sapply(data,dim))
  data_names <- c("gaussian", "binary", "beta-like")
  names(data) <- data_names
  data_t <- data
  data_t[[3]] <- log2(data[[3]]/(1-data[[3]]))
  R <- SolveInt(Y=data_t, p=4, max.it=10, verbose=FALSE, init_flavor="snf", flavor_mod="glmnet")
  R_svd <- SolveInt(Y=data_t, p=4, max.it=10, verbose=FALSE, init_flavor="svd", flavor_mod="glmnet")
  R_random <- SolveInt(Y=data_t, p=4, max.it=10, verbose=FALSE, init_flavor="random", flavor_mod="glmnet")
  R_hclust <- SolveInt(Y=data_t, p=4, max.it=10, verbose=FALSE, init_flavor="hclust", flavor_mod="glmnet")
  df_ari <- data.frame(sim=ii,ARI=c(adjustedRandIndex(clust_function(R), true.clust), 
                                    adjustedRandIndex(clust_function(R_svd), true.clust), adjustedRandIndex(clust_function(R_random), true.clust), adjustedRandIndex(clust_function(R_hclust), true.clust)), method=c("SNF", "SVD", "Random", "hclust"))
  
  df_pve <- data.frame(PVE=c(R$pve, R_svd$pve, R_random$pve, R_hclust$pve), 
                       method= rep(c("SNF","SVD", "Random", "Hclust"),
                                   times=c(length(R$pve),length(R_svd$pve), length(R_random$pve), length(R_hclust$pve) )))
  
  return(list(ari=df_ari, pve=df_pve))
}))
```



## Performance evaluation

```{r}
ARI_dat <-  do.call(rbind, perf[1:20])
g <- ARI_dat %>% ggplot(aes(x=method, fill=method, y=ARI))+geom_violin()+theme_bw()+theme(legend.position = "none")+xlab("")+geom_point(alpha=0.5)
#ggsave(filename = '../../../papers/NAR-LaTeX-20170208/eval_init.png', plot = g, width=7, height=5)
g
```

## Number of iterations
```{r}
pve_dat <- do.call(rbind, lapply(perf[21:40], function(g){
  g <- g %>% group_by(method) %>% mutate(it = row_number())
} ))

g_pve <- pve_dat%>% 
  ggplot(aes(x=it, y=PVE,fill=method)) +
  geom_smooth(se = TRUE, aes(colour=method))+theme_bw()+ theme(legend.position="bottom")+scale_x_continuous(
    breaks = 1:10)
g_pve
#ggsave(filename = '../../../papers/NAR-LaTeX-20170208/pve_init.png', plot = g_pve, width=7, height=5)

```


### Model selection 
```{r, message=FALSE, warning=FALSE}
bics <- do.call(rbind, lapply(1:20, function(ii) {
  penalty <- lapply(2:7, function(p) {
    c_1 <- simulateY(nclust = nclust,  n_byClust = nByclust, J=100, prop=0.05, noise=0.2)
    c_2 <- simulateY(nclust = nclust,  n_byClust = nByclust, J=50, flavor="binary", params=list(c(p=0.6)), prop=0.1, noise=0.3)
    params_beta <- list(c(mean1=-1, mean2=1, sd1=0.5, sd2=0.5))
    c_3 <- simulateY(nclust = nclust,  n_byClust = nByclust, J=500,flavor="beta", params=params_beta, prop=0.2, noise=0.2)
    data <- list(c_1$data, c_2$data, c_3$data)
    data <- lapply(data, function (dd){
      colnames(dd) <- sprintf("gene%s",1:ncol(dd)) 
      dd
    })
    true.clust <- c_1$true.clusters
    print(sapply(data,dim))
    data_names <- c("gaussian", "binary", "beta-like")
    names(data) <- data_names
    data_t <- data
    data_t[[3]] <- log2(data[[3]]/(1-data[[3]]))
    R <- SolveInt(Y=data_t, p=p, max.it=10, verbose=FALSE, init_flavor="snf", flavor_mod="glmnet")
    list(res=R, Y=data_t)
  })
  t <- sapply(penalty, function(pena) (computeLL(Y=pena$Y, res=pena$res) %>% compute_BIC()))
  t(t) %>% as.data.frame %>% mutate(sample=ii)
}))
```


```{r}
g_bic <- bics %>% ggplot(aes(x=p.p, y=BIC.n))+theme_bw()+ geom_line(aes(group = sample), alpha=0.3)+xlab("p")+ylab("BIC")

g_bic
#ggsave(filename = '../../../papers/NAR-LaTeX-20170208/bic_p.png', plot = g_bic, width=7, height=5)


```

