context("Penalized MF algorithm test: SolveInt")
set.seed(33)
W <- rbind(diag(1, nrow = 3, ncol = 3), diag(1, nrow = 3, ncol = 3))
H1 <- as.matrix(rSpMatrix(3, 100, nnz = 10, rand.x= function(nnz) round(rnorm(nnz, 2, 0.2), 2) ))
H2 <- as.matrix(rSpMatrix(3, 100, nnz = 10,  rand.x= function(nnz) round(rnorm(nnz, 2, 0.2), 2) ))
H3 <- as.matrix(rSpMatrix(3, 300, nnz = 10, rand.x= function(nnz) round(rnorm(nnz, 6, 0.2), 2) ))
Y1 <- as.matrix(W%*%H1 + rnorm(20, sd=1))
Y2 <- as.matrix(W%*%H2 + rnorm(20, sd=1))
Y3 <- as.matrix(W%*%H3 + rnorm(20, sd=1))
data <- list(Y1,Y2,Y3)
test_that("CPenalized MF algorithm test", {
  ## solving with PintMF
  R <- PintMF::SolveInt(Y=data, p=3, max.it=1, flavor_mod = "glmnet")
  expect_equal(is.list(R), TRUE)
  expect_equal(is.matrix(R$W), TRUE)
  expect_equal(is.list(R$H), TRUE)
  R <- PintMF::SolveInt(Y=data, p=3, max.it=1, flavor_mod = "ncvreg")
  expect_equal(is.list(R), TRUE)
  expect_equal(is.matrix(R$W), TRUE)
  expect_equal(is.list(R$H), TRUE)
})
