---
title: "microbenchmark"
author: "Morgane Pierre-Jean"
date: "21/02/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{microbenchmark vignette}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Microbenchmark 

We want to assess the performance in times of several penalized methods.

```{r, microb, eval=FALSE}
set.seed(33)
library(PintMF)
W <- rbind(diag(1, nrow = 3, ncol = 3), diag(1, nrow = 3, ncol = 3))
H1 <- as.matrix(rSpMatrix(3, 100, nnz = 20, rand.x= function(nnz) round(rnorm(nnz, 2, 0.2), 2) ))
Y1 <- as.matrix(W%*%H1 + rnorm(20, sd=1))
library(microbenchmark)
mbm = microbenchmark(
  glmnet = PintMF::get.H(W, Y1, flavor_mod = "glmnet", verbose=TRUE),
  ncvreg = PintMF::get.H(W, Y1, flavor_mod = "ncvreg", verbose=TRUE),
  bigmemory = PintMF::get.H(W, Y1, flavor_mod = "biglasso", verbose=TRUE),
  quadrupen = PintMF::get.H(W, Y1, flavor_mod = "quadrupen", verbose=TRUE),times = 20L
)

#ggsave(filename = "../../../papers/NAR-LaTeX-20170208/eval_perf_lasso.eps", width = 6, height = 6)
```
```{r, eval=FALSE}
library(ggplot2)
g <- autoplot(mbm)+theme_bw()
g

```

