---
title: "OMICSSIMLA"
author: "Morgane Pierre-Jean"
date: "28/04/2020"
output: html_document
---

## Intro
Omicssimla simulations

```{r setup}
knitr::opts_knit$set(root.dir = "~/Documents/CEA/Integrating/dev/multiOM/")
```

```{r, path}
getwd()
path_sim <- "../data/OmicsSIMLA_v0.6/sim"
list.files(path_sim)
```

## Proteins

```{r, protein}
ll_prot <- list.files(path_sim, full.names=TRUE, pattern="[.]protein")
prot_dat <- lapply(ll_prot, read.delim,head=FALSE,  sep=" ", stringsAsFactors=FALSE)
head(prot_dat[[1]][,1:10])

cols <- RColorBrewer::brewer.pal(3, "Set1")[c(1,2)]

gplots::heatmap.2(as.matrix(prot_dat[[1]][prot_dat[[1]]$V5 %>% order, -c(1:6, ncol(prot_dat[[1]]))])[, 1:300], trace="none", RowSideColors =cols[prot_dat[[1]]$V5 %>% sort], dendrogram = "col", Rowv = FALSE)

```

## Expression

We simulated 100 genes with DE between cases and controls.
The three dQTM_DE columns correspond to the expression of the three genes influenced by the eQTM.


```{r, exp}
ll_exp <- list.files(path_sim, full.names=TRUE, pattern="[.]nor_exp")
exp_dat <- lapply(ll_exp, read.delim,head=TRUE,  sep=" ", stringsAsFactors=FALSE)

head(exp_dat[[1]][,1:10])
cols <- RColorBrewer::brewer.pal(3, "Set1")[c(1,2)]
df <- exp_dat[[1]] %>% dplyr::select(starts_with("DE"))
clust <- stringr::str_detect(rownames(df), "CASE")+1 
my_palette <- colorRampPalette(c("red", "black", "green"))(n = 299)
gplots::heatmap.2(as.matrix(df[order(clust), ]), trace="none", RowSideColors =cols[clust%>% sort], dendrogram = "col", Rowv = FALSE, col=my_palette)

```
```{r}
df <- exp_dat[[1]] %>% dplyr::select(starts_with("eQTM_DE"))
clust <- stringr::str_detect(rownames(df), "CASE")+1 
gplots::heatmap.2(as.matrix(df[order(clust), ]), trace="none", RowSideColors =cols[clust%>% sort], dendrogram = "col", Rowv = FALSE, col=my_palette)

```

## Methylation

```{r, methy}
ll_methy<- list.files(path_sim, full.names=TRUE, pattern="[.]methy")
methy_dat <- lapply(ll_methy, read.delim,head=FALSE,  sep=" ", stringsAsFactors=FALSE)

head(methy_dat[[1]][,1:10])
sub_methy <- lapply(methy_dat, function (cc){
  df <- cc[,-c(1:3)] %>% apply(2, function(c) {
    df <- data.frame(meth=c) %>% tidyr::separate(meth, c("numCs","tot"), sep=",")%>%
      mutate(numCs=as.numeric(numCs), tot=as.numeric(tot))
    beta =df$numCs/df$tot
    })
  
  na_col <- ncol(df)
  
  df_wo_na <- df[, -na_col]
  rownames(df_wo_na) <- cc$V1
  df_wo_na
})

m <- read.delim(file.path(path_sim, "Methylation_summary.txt"), sep=" ")
cols <- RColorBrewer::brewer.pal(3, "Set1")[c(1,2)]
gplots::heatmap.2(sub_methy[[1]], trace="none", RowSideColors =cols[methy_dat[[1]]$V3], col=my_palette)
```
```{r}
n_batch <- length(sub_methy)
m <- read.delim(file.path(path_sim, "Methylation_summary.txt"), sep=" ")
list_sim <- lapply(1:n_batch, function (b){
  meth = sub_methy[[b]]
  colnames(meth) = m$Pos
  exp = exp_dat[[b]] [, -c(1:6, ncol(exp_dat[[b]]))]
  prot = prot_dat[[b]][, -c(1:6, ncol(prot_dat[[b]]))]
  rownames(prot) <- prot_dat[[b]][,1]
  pat <- rownames(prot) %>% sort
  return(list(meth=meth[pat,], exp=exp[pat,], prot=prot[pat,], methpos=m$Pos[c(which(m$Metylation_type=="eQTM"), which(m$Theta!=0))]))
})
saveRDS(object = list_sim, file="inst/extdata/OMICSSIMLA.rds")
```

